extends: [ standard, standard-react ]
plugins: [ jest ]
env:
  jest/globals: true
rules:
  generator-star-spacing:
    - error
    - before: false
      after: true
  space-before-function-paren: [ error, never ]
