export const actions = {
  FETCH_TODO_LIST: 'FETCH_TODO_LIST',
  FETCH_TODO_LIST_FAILED: 'FETCH_TODO_LIST_FAILED',
  FETCHED_TODO_LIST: 'FETCHED_TODO_LIST',
  ADD_TODO: 'ADD_TODO',
  ADD_TODO_FAILED: 'ADD_TODO_FAILED',
  ADDED_TODO: 'ADDED_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLE_TODO_FAILED: 'TOGGLE_TODO_FAILED',
  TOGGLED_TODO: 'TOGGLED_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
}
